import "./globals.css";
import './entertainmentlist/entertainmentl.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";


const inter = Inter({ subsets: ["latin"] });

const medium = localFont({
  src: "./font/iransansX family/IRANSansX-Medium.ttf",
  variable: "--medium",
});
const regular = localFont({
  src: "./font/iransansX family/IRANSansX-Regular.ttf",
  variable: "--regular",
});

const bold = localFont({
  src: "./font/iransansX family/IRANSansX-Bold.ttf",
  variable: "--bold",
});

const bolder = localFont({
  src: "./font/iransansX family/IRANSansX-ExtraBold.ttf",
  variable: "--bolder",
});


const small = localFont({
  src: "./font/Farsi numerals/IRANSansXFaNum-Light.ttf",
  variable: "--small",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <body
      dir="rtl"
        className={`${regular.variable} ${medium.variable} ${bold.variable} ${small.variable} ${small.variable} ${bolder.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
